### ISSUE TITLE
PythonのフレームワークをFastAPIに変更しようと思います

### ISSUE THREAD

**Issue by dahlia1209** [dahlia1209/hearmetalk#24]
@yuuyeah  @yutyut119 
現在PythonのフレームワークはFlaskを使っており、WebScoket通信できるようにflask_socketioというライブラリを使っていたのですがドキュメントやコミュニティがほぼなく、問題が解決できないまま１か月くらい時間がたってしまったため、思い切ってフレームワーク事態を変えようと思います。
PythonのフレームワークはFlask、Djangoが強いですが、近年人気が出ているFastAPIを使ってみようと思います。FastAPIは軽量なフレームワークで学習コストが低いので開発がしやすく、ドキュメント量も多いということなのでこれから使ってみようと思います。
何かあればコメントお願いします。

**Comment by dahlia1209** [comment]
参考：[２０２２年のPythonフレームワークのシェア率](https://lp.jetbrains.com/ja-jp/python-developers-survey-2022/#FrameworksLibraries)
![image](https://github.com/dahlia1209/hearmetalk/assets/145198667/0c7698f5-641d-416b-a2c4-dc7808af848e)
（サイトから抜粋）
Python ウェブフレームワークの使用については、Flask、Django、FastAPI の三つ巴の戦いが続いています。

他のすべてのフレームワークを合わせても 3 位に届きません。FastAPI は昨年から 4 パーセントポイント増加し、現在では Python 開発者 4 人に 1 人が使用しています。

**Comment by yuuyeah** [comment]
いいと思います！FAST API最近人気ですね
ちなみにどんな問題が起こってますか？

**Comment by dahlia1209** [comment]
@yuuyeah 
返信ありがとうございます
問題としてはTeamsやZoomであるような会議のリアルタイム文字起こしを実装しようとしているのですが、WebSocket通信でサーバーからクライアントにテキストが送れないという事象が起きています。
実装ロジックはクライアントで録音を開始すると録音した音声データを定期的にサーバに送信し、サーバ側でAzureの音声サービスライブラリ（Speech SDK）を使って音声データからテキストデータに変換し、テキストデータをクライアントにレスポンスします。
クライアントからサーバへの音声データの送信、音声データからテキストデータへの変換はうまくいくのですが、クライアントへのレスポンスがにっちもさっちもうまくいかず、結局心折れました。
フロントエンドはVue、バックエンドはFlaskを使っていました。
Flaskでフロントページを生成するようにすればできそうなのですが、フロントはVueで実装したいという思いがあり、FlaskのほうをFastAPIに変えようと思いました。

**Comment by yuuyeah** [comment]
@dahlia1209 
そうなんですね
目指してる構成のアーキテクチャ図とかってありますか？
興味ですがシーケンスが気になりました

**Comment by dahlia1209** [comment]
@yuuyeah 
簡単な機能シーケンス図を送ります。（イメージあってるかな）
<img width="796" alt="リアルタイムテキスト文字起こし機能シーケンス図_20240113" src="https://github.com/dahlia1209/hearmetalk/assets/145198667/fc8f7090-2c1b-4e4b-9deb-e4b439682d01">

**Comment by dahlia1209** [comment]
問題となったのは上記図のテキストデータ送信のWebScoketレスポンスの部分です。ここがうまくレスポンスできません。
![image](https://github.com/dahlia1209/hearmetalk/assets/145198667/726b3233-7771-49cc-abe1-4f0398d8130f)

**Comment by yuuyeah** [comment]
まさにこれが見たかったです！
