### ISSUE TITLE
AIチャット機能を追加しました。

### ISSUE THREAD

**Issue by dahlia1209** [dahlia1209/hearmetalk#25]
@yuuyeah  @yutyut119 
FastAPIに切り替えて初機能を追加しました。
ChatGPTのようにテキストを入力して送信ボタンをクリックすると、回答文が画面上に表示されるようになります。
詳しい動きは下記youtubeにアップしました。
"https://www.youtube.com/watch?v=kwvU1WaDOfM"

**Comment by yuuyeah** [comment]
おおお、すごいですね···!

**Comment by dahlia1209** [comment]
動画埋め込んで別リンクに遷移しなくても再生できるようにしたいのだけど、やり方わかったりしますか？

**Comment by dahlia1209** [comment]
以下HTML要素を埋め込みたいです。
<iframe width="560" height="315" src="https://www.youtube.com/embed/kwvU1WaDOfM?si=ZDw33fekV2QCh9q7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

**Comment by dahlia1209** [comment]
すぐやり方見つからなそうなのでデモの見せ方は考えます。。

**Comment by yuuyeah** [comment]
このコメント内でってことですよね？
多分埋め込みは無理だと思います
gif画像にして画像としてあげるとかはできると思います

**Comment by yuuyeah** [comment]
[[!['altテキスト']('サムネイル画像のURL')]('[Youtube動画のURL](https://www.youtube.com/embed/kwvU1WaDOfM?si=ZDw33fekV2QCh9q7)')](https://www.youtube.com/embed/kwvU1WaDOfM?si=ZDw33fekV2QCh9q7)

**Comment by dahlia1209** [comment]
gif画像です。
![hearmetalk-Google-Chrome-2024-01-16-22-51-01](https://github.com/dahlia1209/hearmetalk/assets/145198667/07144b81-50f2-4432-a64f-b85c8357dd60)

**Comment by dahlia1209** [comment]
gif画像でもいい感じに見れそうですね。ゆうやさんありがとうございます。
